### ISSUE TITLE
manifest fix

### ISSUE THREAD

**Issue by ghost** [Ghent/funtoo-plex#2]
-2017-02-07 23:39:56--  https://downloads.plex.tv/plex-media-server/1.3.4.3285-b46e0ea/plexmediaserver_1.3.4.3285-b46e0ea_amd64.deb
Resolving downloads.plex.tv... 104.20.6.9, 104.20.7.9, 2400:cb00:2048:1::6814:609, ...
Connecting to downloads.plex.tv|104.20.6.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 101356988 (97M) [application/x-deb]
Saving to: ‘/usr/portage/distfiles/plexmediaserver_1.3.4.3285-b46e0ea_amd64.deb’

/usr/portage/distfi 100%[===================>]  96.66M  7.38MB/s    in 13s

2017-02-07 23:40:09 (7.28 MB/s) - ‘/usr/portage/distfiles/plexmediaserver_1.3.4.3285-b46e0ea_amd64.deb’ saved [101356988/101356988]

!!! Fetched file: plexmediaserver_1.3.4.3285-b46e0ea_amd64.deb VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      101356988
!!! Expected: 101364400
Refetching... File renamed to '/usr/portage/distfiles/plexmediaserver_1.3.4.3285-b46e0ea_amd64.deb._checksum_failure_.5taxskix'

!!! Couldn't download 'plexmediaserver_1.3.4.3285-b46e0ea_amd64.deb'. Aborting.
 * Fetch failed for 'media-tv/plex-media-server-1.3.4', Log file:
 *  '/var/tmp/portage/media-tv/plex-media-server-1.3.4/temp/build.log'
 * Please download, depending on your architecture,  either
 *   - plexmediaserver_1.3.4.3285-b46e0ea_i386.deb
 *   - or plexmediaserver_1.3.4.3285-b46e0ea_amd64.deb
 * From http://www.plex.tv/ and move it to /usr/portage/distfiles

>>> Failed to emerge media-tv/plex-media-server-1.3.4, Log file:

>>>  '/var/tmp/portage/media-tv/plex-media-server-1.3.4/temp/build.log'

 * Messages for package media-tv/plex-media-server-1.3.4:

 * Fetch failed for 'media-tv/plex-media-server-1.3.4', Log file:
 *  '/var/tmp/portage/media-tv/plex-media-server-1.3.4/temp/build.log'

**Comment by Ghent** [comment]
Closed via PR #3
